FROM golang:1.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o send-server .

FROM alpine:latest

WORKDIR /app

ENV APP=send-server

COPY --from=builder /app/send-server .

COPY send.html .

COPY firebase-messaging-sw.js .

ENTRYPOINT ["./send-server"]
