FROM golang:1.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o api-server-logger .

FROM alpine:latest

WORKDIR /app

ENV APP=api-server-logger

COPY --from=builder /app/api-server-logger .

ENV GIN_MODE=release

ENTRYPOINT ["./api-server-logger"]
