FROM golang:1.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o receive-server .

FROM alpine:latest

WORKDIR /app

ENV APP=receive-server

COPY --from=builder /app/receive-server .

COPY receive.html .

COPY firebase-messaging-sw.js .

ENTRYPOINT ["./receive-server"]