FROM golang:1.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o api-server .

FROM alpine:latest

WORKDIR /app

ENV APP=api-server

COPY --from=builder /app/api-server .

COPY index.html .

ENV GIN_MODE=release

ENTRYPOINT ["./api-server"]
